---
- name: "python3 | Install packages"
  yum:
    name: [ "python-setuptools", "python3", "python3-devel", "python3-setuptools", "python3-pip" ]
    state: present

- name: "python3 | Install virtualenv"
  pip:
    name: virtualenv
    state: present
    executable: pip3.6
